apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-worker.fullname" . }}-config
  labels:
    {{- include "order-worker.labels" . | nindent 4 }}
data:
  TEMPORAL_ADDRESS: {{ .Values.temporal.address | quote }}
  TASK_QUEUE: {{ .Values.temporal.taskQueue | quote }}
